### ISSUE TITLE
Crash on loadup

### ISSUE THREAD

**Issue by dylanpiera** [dmillerw/Quadrum#12]
Im trying to create a custom log texture when i put it as default texture it works, But when i put in the texture-info to make the top and bottom different it crashes me. even if i add just the texture-info line it will crash me. Can anyone tell me what im doing (Its not the png files or the names checked those multiple times!)

Non crashing config file
{
    "name": "Hydrated-Oak-Wood",
    "default-texture": "Log",
    "material": "wood",
    "hardness": 1,
    "type": "block",
    "drops-self": "true",
    "drops": [],
    "flammable": "true",
    "requires-tool": "false"
}

Crashing Config File
{
    "name": "Hydrated-Oak-Wood",
    "default-texture": "Log",
    "texture-info": {
        "front": "",
        "back": "",
        "left": "",
        "right": "",
        "top": "LogTop",
        "bottom": "LogTop"
    },
    "material": "wood",
    "hardness": 1,
    "type": "block",
    "drops-self": "true",
    "drops": [],
    "flammable": "true",
    "requires-tool": "false"
}

**Comment by ljfa-ag** [comment]
Did you maybe forget a closing } at the end?
