### ISSUE TITLE
Limited to 16x textures?

### ISSUE THREAD

**Issue by Evolution0** [dmillerw/Quadrum#13]
Quadrum seems to be limited to a 16x16 texture size? Tried applying a 32x32 texture and it only grabs the first 16x16 pixels starting from 0,0.

**Comment by kane-thornwyrd** [comment]
Strange, I made it work flawlessly with 128x128 textures.

**Comment by Evolution0** [comment]
Perhaps someday I'll get around to using it again, honestly I didn't try textures larger than 32x32 so it may be a bug with textures of specific sizes or some incompatibility with a mod installed along side it (I believe I had used Fastcraft + Optifine so possible)

Anyway as you can see I posted the issue ages ago and it seems development of Quadrum has stopped though I can't imagine it needing anymore features so maybe its "Stable" and this is a one off bug due to my configuration at the time. Sad if that is the case as I was looking to make Quadrum my first project to contribute to but dropped it after I posted this.

I'll take your word for it and close this.

**Comment by kane-thornwyrd** [comment]
Shameless self-promo, to be sure: if you have the curse launcher, use my modpack "Testbed", add only Quadrum then add your conf, see how it work.
It's standardized, controlled, reproducible environment, should clear any doubt.
http://www.curse.com/modpacks/minecraft/235463-testbed

**Comment by kane-thornwyrd** [comment]
There is clearly an issue in the process of stiching the textures, I obtain alumite crossbow limbs instead of my textures.
