### ISSUE TITLE
[1.10.2] Pack crashes when click onto creative tab or search for item on JEI/NEI

### ISSUE THREAD

**Issue by Jacky1356400** [dmillerw/Quadrum#25]
So I made a couple of items and a block for my modpack, was trying to click on the Quadrum creative tab and see if the items works, but it crashed. Tried searching on JEI/NEI, crashed as well.

Crash report: http://pastebin.com/87xhs3GA
Items/Block Config & Resources: https://drive.google.com/open?id=0B1uNLjT86FhTRHFURlBHc2pFTjQ

I have followed the instructions on Quadrum wiki and Minecraft wiki, hopefully it's not the problem with the config.

**Comment by dmillerw** [comment]
Aware of the issue, attempting to fix now before I have to leave

**Comment by Jacky1356400** [comment]
Thank you so much, appreciated! <3

**Comment by dmillerw** [comment]
Fixed! Grab v0.6.1 from CurseForge

**Comment by Jacky1356400** [comment]
Awesome, thank you once again.
