### ISSUE TITLE
Crops, when implemented, should allow for more than 2 item drops

### ISSUE THREAD

**Issue by Sunconure11** [dmillerw/Quadrum#26]
We have one drop for seeds, one drop for harvests, but what about adding one drop for a rare item? Basically, think a potato, but with more than two possible drops of the item.

Example:

Magic crop one:

Seeds (1 - 3 seeds)
Main harvest (2 - 5 of desired item)
Rare item (1 - 2 of item)

This is based off a dumb idea I had where you a crop that sends out a redstone signal based on its growth stage, with each stage increasing the strength of the signal (it would be based off of wheat in growth stages), and the idea for the rare item is a small pile of redstone dust that, when combined with 8 other piles of small redstone dust, would create 1 redstone dust.

**Comment by dmillerw** [comment]
Will be implemented as part of the Drops trait coming in 0.7.0. Crops will be added in a later version

**Comment by dmillerw** [comment]
Block drops implemented as part of commit a90e27b139bfd6f8d0e0810cde73e36a8d976358
