### ISSUE TITLE
Add an example downloadable file for the wiki.

### ISSUE THREAD

**Issue by JAWSAWN** [dmillerw/Quadrum#27]
1.10 quadrum is much different than the 1.7 one. can we have an example downloadable quadrum "config" and "resources" files? That would explain more than words for some people(like me). 
So like 2 items and 2 blocks would be great, so we can figure it out how to add new ones easily.

Thanks.

**Comment by dmillerw** [comment]
Will do

**Comment by Thiana** [comment]
I'd also like to see this. Preferably separate examples of a single block and a block with variants. Thanks.

**Comment by JAWSAWN** [comment]
Also @dmillerw can I make items with durability with this?

**Comment by dmillerw** [comment]
Not at the moment, it's planned

**Comment by Dilnu** [comment]
Hi, have you made any progress on this? I've tried following the getting started guide on 1.10 but nothing is showing up.
