### ISSUE TITLE
Effective Tools for blocks and block drops

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/Quadrum#28]
At the moment I don't see any way of adding effective tools to added blocks, so I assume it doesn't exist yet.
Blocks also don't seem to have any drops when I try breaking by hand, so a way to add those would be appreciated.

**Comment by dmillerw** [comment]
In progress, will be released as part of 0.7.0

**Comment by dmillerw** [comment]
Implemented as of 43f8229abeb07187687cf6ad8ba3b0f941385b5c
