### ISSUE TITLE
Quadrum not adding blocks/variants defined in json.

### ISSUE THREAD

**Issue by Lgk2** [dmillerw/Quadrum#36]
Hey I'm pretty sure I've done something wrong in terms of the json since the blocks aren't added. The block stopped working when i added 3 different variants so I'm not sure if i did something wrong there or if variants aren't implemented in 1.10.2 yet.

Does all the models and whatnot need to be setup correctly for quadrum to add stuff with variants?

**Comment by SPMoo66** [comment]
Have you tried using a comma after the `"variants": ["hardened_chassis", "reinforced_chassis", "resonant_chassis"]` section?

I think that's what the problem is, but it's only a guess.

**Comment by Lgk2** [comment]
SPMoo probably figured out what I did wrong.
