### ISSUE TITLE
Issue with certain mods

### ISSUE THREAD

**Issue by banjomarx** [dmillerw/Quadrum#4]
i sent you a series of msgs but i didnt recieve a response and i feel like this is a more appropriate place to post it anyways
My friend and I are attempting to get your amazing mod, quadrum, up and running with out modpack, however so far we have been having quite a few issues with not being able to get it working with all of our mods, thought it works for the most part when used without other mods present. i believe he left a more detailed report on the forum page on the minecraft forums, but essentially without other mods the textures are screwed up (only for him not me for some reason) and he cannot even start the modpack with other mods in it (though without quadrum it works just fine) we are eagerly awaiting the ability to use your mod so if you have decided to discontinue it , i would be very grateful if you could tell us so we could know we need to go elsewhere. if you do not wish to consult the forum, i have included the crash report i just received attempting to boot with quadrum in our pack 
http://pastie.org/9557032

through careful selection ive discovered one of the mods causing problems with quadrum (though i'm not sure why) was some mod called cloud storage, im currently looking into what other mods are interfering

ok another mod having problems is the moreswordsmod http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282601-more-swords-mod

for the more swords mod i was using the newest dev snapshot but it had no problems without quadrum so idk

alright by removing those two mods it started working even with all of the rest of our mods (which number over 100 if im not mistaken)

ill also post this on your git if i can find it

**Comment by Carbon-Ghost** [comment]
I have the .transformReplace from Minetweaker doesn't always work with Quadrum in certain crafting inventories other than vanilla.

**Comment by Carbon-Ghost** [comment]
Extra issue
