### ISSUE TITLE
[Request] Item Example 

### ISSUE THREAD

**Issue by TokkenGmr** [dmillerw/Quadrum#41]
So i was attempting to create a basic item to be used in crafting, I based the json on the "block" example and was unable to get it to load. Could you please supply an example of an item json. For instance a new ingot.

**Comment by SPMoo66** [comment]
In `.minecraft/config/quadrum/items/` -> https://pastebin.com/T7d1ifE0
In `.minecraft/resources/quadrum/models/item/` -> https://pastebin.com/0muY1wqg
Put a texture png in `.minecraft/resources/quadrum/textures/items/` with the same file name

Lang entries go `item.quadrum:finite_catalyst.name=Finite Catalyst`
