### ISSUE TITLE
Unable to get items to render, need some assistance

### ISSUE THREAD

**Issue by Sunconure11** [dmillerw/Quadrum#53]
I've been trying to work on a custom ore using this mod, but I can't get it's drop to render. Am I doing something wrong? Here are my associated config and resource files: 
[quadrum.zip](https://github.com/dmillerw/Quadrum/files/2472781/quadrum.zip)

I managed to get the blocks to render fine, but the item refuses to render.

**Comment by Sunconure11** [comment]
Another issue I'm noticing is that the one sole item I added is showing up in every creative tab.

**Comment by PyroBurnem** [comment]
Glad it wasn't just me who has this problem, been pulling my hairs out for hours and hours

**Comment by Sunconure11** [comment]
Going to ping the dev, to see if he's on. @dmillerw

**Comment by dmillerw** [comment]
Sorry for the delay. I'll investigate this tonight

**Comment by CrankySupertoon01** [comment]
i am also having the same bug

**Comment by Sunconure11** [comment]
Sorry to bug you @dmillerw, but any news regarding this?

**Comment by Clinkr1000** [comment]
any progress?  im also having this issue.
