### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Smartaros** [dmillerw/Quadrum#54]
How to fix it?
![bug](https://user-images.githubusercontent.com/26225365/51399827-efc0b780-1b57-11e9-81a6-e0e6dca2dbd9.png)

[code](https://pastebin.com/VxsgnLnu)

**Comment by CREEATION** [comment]
I might be wrong (as I haven't used Quadrum yet), but I'm pretty sure you have to set `full_cube` to `false`, [according to the documentation](https://github.com/dmillerw/Quadrum/wiki/Visual-(Block)#full-cube) (default is `true`).
