### ISSUE TITLE
Fastcraft Vs Quadrum crash

### ISSUE THREAD

**Issue by Mimung** [dmillerw/Quadrum#8]
Fastcraft 1.9 or Quadrum 1.2.0.B13 crashes at startup when both mods are in the mod-folder. (Forge 10.13.1.1224)

Crash-report:
http://pastebin.com/ehtJUYSb 

This is also posted over at the Fastcraft forumthread.
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

**Comment by BarbasTheDog** [comment]
Can confirm.

Crash report:
http://pastebin.com/XnDAYXmt
(Don't mind the title of the paste saying it's version B8, it's actually B13. I was confused because you forgot to update the mcmod.info since version B8.)

Forge Ver.: 1270

**Comment by kane-thornwyrd** [comment]
happen here too when using texture-info.
